// <auto-generated />
namespace StoryScore.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class teamidonplayers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(teamidonplayers));
        
        string IMigrationMetadata.Id
        {
            get { return "201909292014129_teamid-on-players"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
